import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class birthday_theme_selection extends javax.swing.JFrame {
Connection con;
    ResultSet rs;
    Statement stmt;
    PreparedStatement pst;
    String sql="select * from events natural join other_themes where theme_name=?";
    /**
     * Creates new form birthday_theme_selection
     */
    public birthday_theme_selection() {
        initComponents();
        con= DBConnect.connectMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theme = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        simpleRBN = new javax.swing.JRadioButton();
        teenyRBN = new javax.swing.JRadioButton();
        adultsRBN = new javax.swing.JRadioButton();
        floralRBN = new javax.swing.JRadioButton();
        royalRBN = new javax.swing.JRadioButton();
        cartoonRBN = new javax.swing.JRadioButton();
        nextBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1000, 445));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("select your's theme:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 230, 30);

        priceTF.setEditable(false);
        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        getContentPane().add(priceTF);
        priceTF.setBounds(100, 60, 80, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("price:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 60, 50, 20);

        theme.add(simpleRBN);
        simpleRBN.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        simpleRBN.setForeground(java.awt.Color.white);
        simpleRBN.setText(" S I M P L E");
        simpleRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleRBNActionPerformed(evt);
            }
        });
        getContentPane().add(simpleRBN);
        simpleRBN.setBounds(310, 220, 120, 20);

        theme.add(teenyRBN);
        teenyRBN.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        teenyRBN.setForeground(new java.awt.Color(240, 240, 240));
        teenyRBN.setText("T E E N Y");
        teenyRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teenyRBNActionPerformed(evt);
            }
        });
        getContentPane().add(teenyRBN);
        teenyRBN.setBounds(320, 390, 110, 20);

        theme.add(adultsRBN);
        adultsRBN.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        adultsRBN.setForeground(new java.awt.Color(240, 240, 240));
        adultsRBN.setText("A D U L T S");
        adultsRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultsRBNActionPerformed(evt);
            }
        });
        getContentPane().add(adultsRBN);
        adultsRBN.setBounds(810, 390, 120, 20);

        theme.add(floralRBN);
        floralRBN.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        floralRBN.setForeground(new java.awt.Color(240, 240, 240));
        floralRBN.setText("F L O R A L");
        floralRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floralRBNActionPerformed(evt);
            }
        });
        getContentPane().add(floralRBN);
        floralRBN.setBounds(570, 220, 120, 20);

        theme.add(royalRBN);
        royalRBN.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        royalRBN.setForeground(new java.awt.Color(240, 240, 240));
        royalRBN.setText("R O Y A L");
        royalRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                royalRBNActionPerformed(evt);
            }
        });
        getContentPane().add(royalRBN);
        royalRBN.setBounds(580, 390, 110, 20);

        theme.add(cartoonRBN);
        cartoonRBN.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        cartoonRBN.setForeground(new java.awt.Color(240, 240, 240));
        cartoonRBN.setText("C A R T O O N");
        cartoonRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartoonRBNActionPerformed(evt);
            }
        });
        getContentPane().add(cartoonRBN);
        cartoonRBN.setBounds(790, 220, 140, 20);

        nextBTN.setBackground(new java.awt.Color(0, 0, 0));
        nextBTN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nextBTN.setForeground(new java.awt.Color(240, 240, 240));
        nextBTN.setText(" N E X T > >");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });
        getContentPane().add(nextBTN);
        nextBTN.setBounds(70, 310, 110, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/birthday.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -6, 1090, 420);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-338)/2, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFActionPerformed

    private void simpleRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleRBNActionPerformed
        String theme="simple";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,theme);
            rs=pst.executeQuery();
            if(rs.next()){

                priceTF.setText(rs.getInt("charges")+"");

            }
            pst.close();
            rs.close();
        }    catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_simpleRBNActionPerformed

    private void floralRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floralRBNActionPerformed
        String theme="floral";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,theme);
            rs=pst.executeQuery();
            if(rs.next()){

                priceTF.setText(rs.getInt("charges")+"");

            }
            pst.close();
            rs.close();
        }    catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_floralRBNActionPerformed

    private void cartoonRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartoonRBNActionPerformed
        String theme="cartoon";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,theme);
            rs=pst.executeQuery();
            if(rs.next()){

                priceTF.setText(rs.getInt("charges")+"");

            }
            pst.close();
            rs.close();
        }    catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cartoonRBNActionPerformed

    private void teenyRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teenyRBNActionPerformed
        String theme="teeny";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,theme);
            rs=pst.executeQuery();
            if(rs.next()){

                priceTF.setText(rs.getInt("charges")+"");

            }
            pst.close();
            rs.close();
        }    catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_teenyRBNActionPerformed

    private void adultsRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultsRBNActionPerformed
        String theme="adults";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,theme);
            rs=pst.executeQuery();
            if(rs.next()){

                priceTF.setText(rs.getInt("charges")+"");

            }
            pst.close();
            rs.close();
        }    catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_adultsRBNActionPerformed

    private void royalRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_royalRBNActionPerformed
          String theme="royal";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,theme);
            rs=pst.executeQuery();
            if(rs.next()){

                priceTF.setText(rs.getInt("charges")+"");
            }
            pst.close();
            rs.close();
        }    catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_royalRBNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        new Function_Hall().setVisible(true);
        dispose();
    }//GEN-LAST:event_nextBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(birthday_theme_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(birthday_theme_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(birthday_theme_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(birthday_theme_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new birthday_theme_selection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adultsRBN;
    private javax.swing.JRadioButton cartoonRBN;
    private javax.swing.JRadioButton floralRBN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton nextBTN;
    private javax.swing.JTextField priceTF;
    private javax.swing.JRadioButton royalRBN;
    private javax.swing.JRadioButton simpleRBN;
    private javax.swing.JRadioButton teenyRBN;
    private javax.swing.ButtonGroup theme;
    // End of variables declaration//GEN-END:variables
}
