import java.sql.*;
import javax.swing.JOptionPane;

public class Final extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement stmt;
    PreparedStatement pst;
    
    public Final() {
        initComponents();
         con = DBConnect.connectMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eventCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        functionhallCB = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        foodCB = new javax.swing.JComboBox();
        okBTN = new javax.swing.JButton();
        proceedBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        imgLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 588);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("FINAL DECISION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 330, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("EMAIL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 60, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("YOUR EVENT ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 180, 130, 30);
        getContentPane().add(emailTF);
        emailTF.setBounds(300, 110, 220, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 290, 0, 0);

        eventCB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        eventCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reception", "Wedding", "Birthday", "Engagement", "Official" }));
        getContentPane().add(eventCB);
        eventCB.setBounds(300, 180, 220, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("FUNCTION HALL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 230, 160, 60);

        functionhallCB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        functionhallCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ballroom", "Marigold" }));
        getContentPane().add(functionhallCB);
        functionhallCB.setBounds(300, 250, 300, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("FOOD");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 320, 51, 20);

        foodCB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "North Indian", "South Indian" }));
        getContentPane().add(foodCB);
        foodCB.setBounds(300, 310, 300, 30);

        okBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        okBTN.setText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });
        getContentPane().add(okBTN);
        okBTN.setBounds(250, 400, 70, 30);

        proceedBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        proceedBTN.setText("PROCEED");
        proceedBTN.setEnabled(false);
        proceedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBTNActionPerformed(evt);
            }
        });
        getContentPane().add(proceedBTN);
        proceedBTN.setBounds(440, 480, 130, 40);

        backBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN);
        backBTN.setBounds(50, 480, 85, 40);

        imgLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/finalbg1.jpg"))); // NOI18N
        getContentPane().add(imgLBL);
        imgLBL.setBounds(-5, 0, 620, 620);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-631)/2, (screenSize.height-656)/2, 631, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
      new Choose_Food().setVisible(true);
      dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        String email=emailTF.getText();
        String event= eventCB.getSelectedItem()+"";
        String functionhall= functionhallCB.getSelectedItem()+"";
        String food= foodCB.getSelectedItem()+"";
        if(emailTF.getText()!=null)
        {
        String sql = "insert into CUSTOMER_EVENTS(email,event_booked,function_hall,food) values(?,?,?,?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1,email );
            pst.setString(2, event);
            pst.setString(3,functionhall);
            pst.setString(4,food);
            pst.executeUpdate();
         }
         
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e.getMessage());
         }
         proceedBTN.setEnabled(true);
        }
        
      
        
    }//GEN-LAST:event_okBTNActionPerformed

    private void proceedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBTNActionPerformed
        new LastFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_proceedBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JTextField emailTF;
    private javax.swing.JComboBox eventCB;
    private javax.swing.JComboBox foodCB;
    private javax.swing.JComboBox functionhallCB;
    private javax.swing.JLabel imgLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okBTN;
    private javax.swing.JButton proceedBTN;
    // End of variables declaration//GEN-END:variables
}
