public class Homepage extends javax.swing.JFrame {

    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adminloginBTN = new javax.swing.JButton();
        custloginBTN = new javax.swing.JButton();
        signupBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bodoni MT Condensed", 2, 36)); // NOI18N
        jLabel3.setText("An awesome way ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 240, 550, 60);

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel2.setText("WELCOME TO DIVINE FIESTA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 10, 680, 90);

        jLabel4.setFont(new java.awt.Font("Bodoni MT Condensed", 2, 36)); // NOI18N
        jLabel4.setText("to make your life beautiful");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 310, 310, 43);

        adminloginBTN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        adminloginBTN.setText("ADMIN LOGIN");
        adminloginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(adminloginBTN);
        adminloginBTN.setBounds(430, 400, 230, 50);

        custloginBTN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        custloginBTN.setText("CUSTOMER LOGIN");
        custloginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custloginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(custloginBTN);
        custloginBTN.setBounds(30, 400, 280, 50);

        signupBTN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        signupBTN.setText("SIGNUP AS CUSTOMER");
        signupBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBTNActionPerformed(evt);
            }
        });
        jPanel1.add(signupBTN);
        signupBTN.setBounds(360, 500, 310, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/3-white-color-decorations-muslim-wedding.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-735)/2, (screenSize.height-609)/2, 735, 609);
    }// </editor-fold>//GEN-END:initComponents

    private void custloginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custloginBTNActionPerformed
        new login_form().setVisible(true);
        dispose();

    }//GEN-LAST:event_custloginBTNActionPerformed

    private void adminloginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginBTNActionPerformed
        new NewJFrame_1().setVisible(true);
        dispose();
    }//GEN-LAST:event_adminloginBTNActionPerformed

    private void signupBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBTNActionPerformed
        new SignUp().setVisible(true);
        dispose();
    }//GEN-LAST:event_signupBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminloginBTN;
    private javax.swing.JButton custloginBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signupBTN;
    // End of variables declaration//GEN-END:variables
}
